# Generated by Django 3.2 on 2023-08-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20230807_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='visibility',
            field=models.CharField(max_length=10, null=True, verbose_name='Видимость'),
        ),
    ]
