# Generated by Django 3.2 on 2023-08-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_books_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='index',
            field=models.IntegerField(null=True, verbose_name='id'),
        ),
    ]
