# Generated by Django 3.2 on 2023-08-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_books_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='index',
            field=models.IntegerField(null=True, unique=True, verbose_name='id'),
        ),
    ]
